# Generated by Django 5.0.6 on 2024-05-26 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_customer_email_remove_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': (('send_private_email', 'Can send private email to user by the button'),)},
        ),
    ]
